name: Terraform

on:
  push:

permissions:
  id-token: write # obrigatório para usar autenticação OIDC
  contents: read # obrigatório para clonar o código do repositório

jobs:
  terraform:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME}}
          role-duration-seconds: ${{ secrets.AWS_ROLE_DURATION_SECONDS }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/main') }}
        run: terraform plan
        env:
          TF_LOG: DEBUG

      - name: Terraform Refresh
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: terraform refresh
        env:
          TF_LOG: DEBUG

      - name: Terraform Apply
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        run: terraform apply -auto-approve
        env:
          TF_LOG: DEBUG

  create-pull-request:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Branch Name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF)" >> $GITHUB_ENV

      - name: Create Pull Request Develop
        if: ${{ success() &&  startsWith(github.ref, 'refs/heads/feature/')}}
        uses: peter-evans/create-pull-request@v6
        with:
          title: PR criado automaticamente
          body: Caso seu build de feature for realizado com sucesso, você poderá seguir para o planejamento de sua infra na develop
          base: develop
          branch: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create Pull Request Main
        if: ${{ success() &&  startsWith(github.ref, 'refs/heads/develop')}}
        uses: peter-evans/create-pull-request@v6
        with:
          title: PR criado automaticamente
          body: Caso seu build de feature for realizado com sucesso, você poderá seguir para o planejamento de sua infra na develop
          base: main
          branch: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
